project:
  type: book

book:
  title: "Quantifying Art Historical Narratives"
  author: "Holland Stam"
  date: "April 8, 2022"
  chapters:
    - acknowledgements.qmd
    - index.qmd
    - 01-intro.qmd
    - 02-methodology.qmd
    - 03-results.qmd
    - 04-discussion.qmd
    - 05-appendix.qmd
    - 06-bibliography.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  echo: false
  warning: false
  freeze: auto
